#default:
#  tags:
#    - my-runner

image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
  - build
  - test
  - release

before_script:
  - "cd EPAM.DreamTour"
  - "dotnet restore"

build:
  stage: build
  script:
    - dotnet build
  artifacts:
    paths:
      - EPAM.DreamTour

test:
  stage: test
  script:
    - dotnet test
